site_name: VIEPS Geodynamics
site_author: Louis Moresi
site_dir: www

## Add the pages you want built here
#
#  The hierarchy of the list describes how these pages will be represented in the navigation
#  bar at the top of the page. Either as individual links or as a dropdown menu of links

pages:
- Home: index.md
- Site Map: SiteMap.md
- Course:
    - "1 - Introduction":            Introduction/index.md
    - "2 - Mantle Convection":       MantleConvection/index.md
    - "3 - Dynamic Topography":      DynamicTopography/index.md
    - "4 - Rheology & Localisation": Rheology/index.md
    - "5 - Subduction zones":        Subduction/index.md
    - "Assessment":                  Assessment/index.md

- Notes:
    - "Introduction To Geodynamics": ComputationalGeodynamics/TheoreticalBackground/index.md
    - "Numerical Methods":           ComputationalGeodynamics/NumericalMethodsPrimer/index.md
    - "Underworld User Guides":      Underworld/index.md
    - "Selected Lecture Materials":  LectureNotes/index.md

- _JustBuildThese:  # not added to the navigation menu
    - ComputationalGeodynamics/index.md
    - ComputationalGeodynamics/TheoreticalBackground/MathPhysicsBackground-1.md
    - ComputationalGeodynamics/TheoreticalBackground/MathPhysicsBackground-2.md
    - ComputationalGeodynamics/TheoreticalBackground/MathPhysicsBackground-3.md
    - ComputationalGeodynamics/TheoreticalBackground/MathPhysicsBackground-4.md
    - ComputationalGeodynamics/NumericalMethodsPrimer/NumericalMethodsPrimer-1.md
    - ComputationalGeodynamics/NumericalMethodsPrimer/NumericalMethodsPrimer-2.md
    - ComputationalGeodynamics/NumericalMethodsPrimer/NumericalMethodsPrimer-3.md
    - ComputationalGeodynamics/NumericalMethodsPrimer/NumericalMethodsPrimer-4.md
    - ComputationalGeodynamics/NumericalMethodsPrimer/NumericalMethodsPrimer-5.md
    - ComputationalGeodynamics/NumericalMethodsPrimer/NumericalMethodsPrimer-6.md

## Here is how to add extra (usually external) links to the navigation bar
#
# 1) Add a link to the nav bar
#     The item you add is a two-member list: ["Name for the link", "url"]
# 2) Add a new menu item to the nav bar
#     The item you add is a three-or-more-member list with a name for the menu item as the first member
#     and subsequent entries being lists of names / urls as above:
#     [ "Menu name", ["Menu item 1 name", "Menu item 1 url"], ["Menu item 2 name", "Menu item 2 url"], ... ]
#

extra:
    nav_links:
        - ["Live Content",
            ["File Browser", "/notebooks/www/" ],
            ["Terminal", "/terminals/1" ],
            ["Console",  "/tree/Notebooks#running" ]
          ]
        - ["Assessment",
            ["In Class Assessment", "/tree/www/Assessment/InClassProblemSets"],
            ["Take Home Assessment", "/tree/www/Assessment/TakeHomeProblemSets"],
          ]




## No need to change these config options unless you want to change the theme or the
#  layout of the navigation bar.
#
#  Some of these options are not intuitive so take care !

# theme over-ride

theme_dir: jupyter-server-theme
theme: flatly

# Layout of pages

use_directory_urls: False

# Mathematics

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/mathjax-local-config.js

markdown_extensions:
    - attr_list
    - def_list
