FROM debian:jessie

# Should lock that down to a specific version !

MAINTAINER Louis Moresi

## the update is fine but very slow ... keep it separated so it doesn't
## get run again and break the cache. The later parts of this build
## may be sensitive to later versions being picked up in the install phase.

RUN apt-get update -y ;

# install everything required
RUN DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        bash-completion \
        build-essential \
        git \
        python \
        python-dev \
        petsc-dev \
        libhdf5-openmpi-dev \
        python-pip \
        libxml2-dev \
        xorg-dev \
        ssh \
        curl \
        libfreetype6-dev \
        libpng12-dev \
        libxft-dev \
        xvfb \
        freeglut3 \
        freeglut3-dev \
        libgl1-mesa-dri \
        libgl1-mesa-glx \
        rsync \
        vim \
        less \
        xauth \
        swig && \
    pip install \
        numpy \
        jupyter \
        plotly \
        mpi4py \
        matplotlib \
        runipy \
        pillow


# set working directory to /root
RUN mkdir -p /underworld
WORKDIR /underworld

# setup environment
ENV PYTHONPATH $PYTHONPATH:/underworld/underworld2

# get underworld, compile, delete some unnecessary files, trust notebooks, copy to workspace
RUN git clone --branch "development" --single-branch https://github.com/underworldcode/underworld2 && \
    cd underworld2/libUnderworld && \
    ./configure.py               && \
    ./scons.py                   && \
    cd libUnderworldPy           && \
    ./swigall.py                 && \
    cd ..                        && \
    ./scons.py                   && \
    rm .sconsign.dblite          && \
    rm -fr .sconf_temp           && \
    cd build                     && \
    rm -fr libUnderworldPy       && \
    rm -fr StGermain             && \
    rm -fr gLucifer              && \
    rm -fr Underworld            && \
    rm -fr StgFEM                && \
    rm -fr StgDomain             && \
    rm -fr PICellerator          && \
    rm -fr Solvers

RUN    find /underworld/underworld2/docs -name \*.ipynb | xargs jupyter trust && \
        mkdir -p  /workspace                                                 && \
        rsync -av /underworld/underworld2/docs/examples /workspace             && \
        rsync -av /underworld/underworld2/docs/user_guide /workspace           && \
        rsync -av /underworld/underworld2/docs/publications /workspace

# expose notebook port
EXPOSE 8888

# setup space for working in
WORKDIR /workspace

RUN useradd --create-home --home-dir /home/profldiablo --shell /bin/bash --user-group profldiablo
RUN chown -R profldiablo:profldiablo /underworld

# But we can't really use this since the installation is in /root !

# USER profldiablo
# ENV USER=profldiablo
#
# RUN     apt-get clean && \
#         rm -rf /var/lib/apt/lists/*

CMD /bin/bash

# launch notebook
# CMD ["jupyter", "notebook", " --no-browser"]
