FROM lmoresi/docker-vieps-geo:2018.1

## =============================================================
## base - image ... whatever functionality you want to provide !
## This is the underworld dev image with some altered defaults.
##
## This just substitutes the run command and opens the relevant ports
##
## =============================================================

# This is best done within the container from the root directory
# when the container is running (particularly if the build area
# is external )
# RUN ./scripts/run-sitebuilder8.py

RUN mkdir build && \
    mkdir build/www1 && \
    mkdir build/www2 && \
    mkdir build/www3 && \
    mkdir build/www4 && \
    mkdir build/www5 && \
    mkdir build/www6 && \
    mkdir build/www7 && \
    mkdir build/www8


# Launch the notebook server from the Notebook directory
# but perhaps there is something else that would do this.

EXPOSE 8080 8081 8082 8082 8084 8085 8086 8087 8088

CMD scripts/run-jupyter8.py
